n_instances: 16  # Number of recent instances to fetch metrics for
fetch_period: 3  # Time range (in hours) to fetch metrics for

csv_dir: ./test/csv  # Directory where CSV files will be saved
graph_dir: ./test/graph # Directory where graphs will be saved

metrics_to_fetch:  # List of CloudWatch metrics to fetch
    - CPUUtilization:
        graph_title: T3-Unlimited CPUUtilization  # Graph title
    - CPUCreditUsage:
        graph_title: T3-Unlimited CPUCreditUsage
    - CPUCreditBalance:
        graph_title: T3-Unlimited CPUCreditUsage
    - CPUSurplusCreditBalance:
        graph_title: T3-Unlimited CPUSurplusCreditBalance
    - CPUSurplusCreditsCharged:
        graph_title: T3-Unlimited CPUSurplusCreditsCharged

