n_instances: 16  # Number of recent instances to fetch metrics for
fetch_period: 3  # Time range (in hours) to fetch metrics for

csv_dir: ./SMB/16Node/M5/exec1/csv  # Directory where CSV files will be saved
graph_dir: ./SMB/16Node/M5/exec1/graph # Directory where graphs will be saved

metrics_to_fetch:  # List of CloudWatch metrics to fetch
    - CPUUtilization:
        graph_title: M5 CPUUtilization  # Graph title

